site_name: SOSC2019 
theme:
  name: material
  logo:
    icon: cloud_circle
  palette:
    primary: 'Deep Purple'
    accent: 'Green'
nav:
- Home: 'README.md'
- PaaS Orchestration: 'orchent.md' 
- Container Orchestration: 'k3s.md'
- Setting up FaaS platform: 'openfaas.md'
- Functions 101: 'events.md'
- Workflows and triggers: 'workflows.md'
repo_url: 'https://github.com/Cloud-PG/SOSC2019'
